import type { ExcludePreset, IceBoxFilterConfig, FilterPattern, PatternType } from "@/types";
import { expandPresets, getExcludePresets, getWhitelistPresets } from "./filter-presets";

interface ResolvedFilterPattern extends FilterPattern {
  source: "preset" | "custom";
  presetId?: string;
  presetName?: string;
}

function getPresetCollection(mode: IceBoxFilterConfig["mode"]): ExcludePreset[] {
  if (mode === "whitelist") {
    return getWhitelistPresets();
  }

  return getExcludePresets();
}

function normalizePattern(pattern: string): string {
  return pattern.replace(/\\r?\\n/g, "").trim();
}

function escapeMarkdownCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, "<br />");
}

function escapeForSingleQuotedShell(value: string): string {
  return value.replace(/'/g, `'"'"'`);
}

function toResolvedFilterPatterns(config: IceBoxFilterConfig): ResolvedFilterPattern[] {
  const presets = getPresetCollection(config.mode);
  const selectedPresetIds = new Set(config.presets);
  const presetMap = new Map(presets.map((preset) => [preset.id, preset]));
  const resolved: ResolvedFilterPattern[] = [];
  const seen = new Set<string>();

  for (const presetId of config.presets) {
    const preset = presetMap.get(presetId);

    if (!preset || !selectedPresetIds.has(presetId)) {
      continue;
    }

    for (const pattern of preset.patterns) {
      const normalized = normalizePattern(pattern.pattern);
      const key = `${pattern.type}:${normalized}`;

      if (!normalized || seen.has(key)) {
        continue;
      }

      seen.add(key);
      resolved.push({
        ...pattern,
        pattern: normalized,
        source: "preset",
        presetId: preset.id,
        presetName: preset.name,
      });
    }
  }

  for (const pattern of config.patterns) {
    const normalized = normalizePattern(pattern.pattern);
    const key = `${pattern.type}:${normalized}`;

    if (!normalized || seen.has(key)) {
      continue;
    }

    seen.add(key);
    resolved.push({
      ...pattern,
      pattern: normalized,
      source: "custom",
    });
  }

  return resolved;
}

// 1. 展开完整的过滤规则（预设 + 自定义）
export function resolveFilterPatterns(config: IceBoxFilterConfig): FilterPattern[] {
  const presets = getPresetCollection(config.mode);
  const presetPatterns = expandPresets(config.presets, presets).map((pattern) => ({
    ...pattern,
    pattern: normalizePattern(pattern.pattern),
  }));

  const resolved: FilterPattern[] = [];
  const seen = new Set<string>();

  for (const pattern of [...presetPatterns, ...config.patterns]) {
    const normalized = normalizePattern(pattern.pattern);
    const key = `${pattern.type}:${normalized}`;

    if (!normalized || seen.has(key)) {
      continue;
    }

    seen.add(key);
    resolved.push({
      ...pattern,
      pattern: normalized,
    });
  }

  return resolved;
}

// 2. 生成 shell 脚本可用的过滤逻辑
// 返回 { globs: string[], regexes: string[] }
export function splitPatternsByType(patterns: FilterPattern[]): { globs: string[]; regexes: string[] } {
  const globs: string[] = [];
  const regexes: string[] = [];
  const seen = new Set<string>();

  for (const pattern of patterns) {
    const normalized = normalizePattern(pattern.pattern);
    const key = `${pattern.type}:${normalized}`;

    if (!normalized || seen.has(key)) {
      continue;
    }

    seen.add(key);

    if (pattern.type === "regex") {
      regexes.push(normalized);
      continue;
    }

    globs.push(normalized);
  }

  return { globs, regexes };
}

// 3. 生成 git exclude 文件内容
export function generateGitExcludeContent(config: IceBoxFilterConfig): string {
  if (config.mode !== "blacklist") {
    return "# git exclude rules are only generated for blacklist mode\n";
  }

  const { globs, regexes } = splitPatternsByType(resolveFilterPatterns(config));
  const lines: string[] = [
    "# Generated by Ice Box backup filter",
    "# Mode: blacklist",
  ];

  if (config.inheritGitignore) {
    lines.push("# inheritGitignore: true (existing .gitignore rules still apply when git honors them)");
  }

  if (globs.length > 0) {
    lines.push("", "# Glob rules");
    lines.push(...globs);
  }

  if (regexes.length > 0) {
    lines.push(
      "",
      "# Regex rules below are informational only; git exclude files do not support regex.",
      ...regexes.map((pattern) => `# regex: ${pattern}`),
    );
  }

  if (globs.length === 0 && regexes.length === 0) {
    lines.push("", "# No custom exclude rules configured");
  }

  return `${lines.join("\n")}\n`;
}

// 4. 生成白名单检查脚本片段（bash）
export function generateWhitelistCheckScript(config: IceBoxFilterConfig): string {
  const patterns = config.mode === "whitelist" ? resolveFilterPatterns(config) : [];
  const { globs, regexes } = splitPatternsByType(patterns);

  const globLines = globs.map((pattern) => `    '${escapeForSingleQuotedShell(pattern)}'`).join("\n");
  const regexLines = regexes.map((pattern) => `    '${escapeForSingleQuotedShell(pattern)}'`).join("\n");

  return [
    "ice_box_is_whitelisted_path() {",
    '  local path="$1"',
    "  local glob",
    "  local regex",
    "",
    "  local -a whitelist_globs=(",
    globLines || "",
    "  )",
    "  local -a whitelist_regexes=(",
    regexLines || "",
    "  )",
    "",
    "  if [ ${#whitelist_globs[@]} -eq 0 ] && [ ${#whitelist_regexes[@]} -eq 0 ]; then",
    "    return 1",
    "  fi",
    "",
    '  for glob in "${whitelist_globs[@]}"; do',
    '    if [[ -n "$glob" && "$path" == $glob ]]; then',
    "      return 0",
    "    fi",
    "  done",
    "",
    '  for regex in "${whitelist_regexes[@]}"; do',
    '    if [[ -n "$regex" && "$path" =~ $regex ]]; then',
    "      return 0",
    "    fi",
    "  done",
    "",
    "  return 1",
    "}",
    "",
  ].join("\n");
}

// 5. 验证正则表达式是否有效
export function validateRegexPattern(pattern: string): { valid: boolean; error?: string } {
  try {
    // eslint-disable-next-line no-new
    new RegExp(pattern);
    return { valid: true };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : "Unknown regex validation error",
    };
  }
}

// 6. 格式化过滤规则用于 Skill 文档
export function formatFilterRulesForMarkdown(config: IceBoxFilterConfig): string {
  const resolved = toResolvedFilterPatterns(config);
  const lines: string[] = [
    `- 模式：\`${config.mode}\``,
    `- 继承 .gitignore：${config.inheritGitignore ? "是" : "否"}`,
  ];

  if (resolved.length === 0) {
    lines.push("", "未配置任何过滤规则。");
    return lines.join("\n");
  }

  lines.push(
    "",
    "| 来源 | 类型 | 模式 | 说明 |",
    "| --- | --- | --- | --- |",
  );

  for (const pattern of resolved) {
    const source =
      pattern.source === "preset"
        ? `预设: ${pattern.presetName ?? pattern.presetId ?? "unknown"}`
        : "自定义";

    const description = pattern.description?.trim() || "-";

    lines.push(
      `| ${escapeMarkdownCell(source)} | ${escapeMarkdownCell(pattern.type)} | \`${escapeMarkdownCell(pattern.pattern)}\` | ${escapeMarkdownCell(description)} |`,
    );
  }

  return lines.join("\n");
}
