import { describe, expect, it } from 'vitest'

import {
  formatFilterRulesForMarkdown,
  generateGitExcludeContent,
  generateWhitelistCheckScript,
  resolveFilterPatterns,
  splitPatternsByType,
  validateRegexPattern,
} from '@/lib/backup-filter'
import type { IceBoxFilterConfig } from '@/types'

const blacklistConfig: IceBoxFilterConfig = {
  mode: 'blacklist',
  presets: ['nodejs'],
  inheritGitignore: true,
  patterns: [
    { pattern: 'custom/**', type: 'glob', description: '自定义目录' },
    { pattern: '^private/.+$', type: 'regex', description: '私有目录' },
    { pattern: 'node_modules/**', type: 'glob', description: '重复规则会被去重' },
    { pattern: '   ', type: 'glob', description: '空白规则会被忽略' },
  ],
}

const whitelistConfig: IceBoxFilterConfig = {
  mode: 'whitelist',
  presets: ['essential', 'no-skills'],
  inheritGitignore: false,
  patterns: [
    { pattern: 'workspace/custom/**', type: 'glob', description: '额外保留' },
    { pattern: '^notes/.+$', type: 'regex', description: '笔记目录' },
  ],
}

describe('backup-filter', () => {
  it('resolveFilterPatterns 合并预设和自定义规则', () => {
    const patterns = resolveFilterPatterns(blacklistConfig)

    expect(patterns).toContainEqual({ pattern: 'node_modules/**', type: 'glob', description: 'Node.js 依赖目录' })
    expect(patterns).toContainEqual({ pattern: 'custom/**', type: 'glob', description: '自定义目录' })
    expect(patterns).toContainEqual({ pattern: '^private/.+$', type: 'regex', description: '私有目录' })
    expect(patterns.filter((item) => item.pattern === 'node_modules/**' && item.type === 'glob')).toHaveLength(1)
  })

  it('splitPatternsByType 正确分类 glob 和 regex', () => {
    const patterns = resolveFilterPatterns(blacklistConfig)
    const result = splitPatternsByType(patterns)

    expect(result.globPatterns.some((item) => item.pattern === 'custom/**')).toBe(true)
    expect(result.regexPatterns).toEqual([
      { pattern: '^private/.+$', type: 'regex', description: '私有目录' },
    ])
  })

  it('generateGitExcludeContent 生成正确的 exclude 内容', () => {
    const content = generateGitExcludeContent(blacklistConfig)

    expect(content).toContain('# Generated by Claw-Fridge backup filter')
    expect(content).toContain('# Local .gitignore remains effective during git add')
    expect(content).toContain('node_modules/**')
    expect(content).toContain('custom/**')
    expect(content).toContain('# regex:^private/.+$')
    expect(content.endsWith('\n')).toBe(true)
  })

  it('generateWhitelistCheckScript 生成正确的 bash 函数', () => {
    const script = generateWhitelistCheckScript(whitelistConfig)

    expect(script).toContain('matches_whitelist_path() {')
    expect(script).toContain('case "$path" in')
    expect(script).toContain('workspace/custom/**) return 0 ;;')
    expect(script).toContain("grep -E --quiet '^(?!skills(?:/|$)).+'")
    expect(script).toContain("grep -E --quiet '^notes/.+$'")
    expect(script).toContain('return 1')
    expect(script.endsWith('\n')).toBe(true)
  })

  it('validateRegexPattern 验证正则表达式', () => {
    expect(validateRegexPattern('^workspace/.+$')).toEqual({ valid: true, error: null })
    expect(validateRegexPattern('[').valid).toBe(false)
  })

  it('formatFilterRulesForMarkdown 生成 markdown 表格/列表说明', () => {
    const markdown = formatFilterRulesForMarkdown(whitelistConfig)

    expect(markdown).toContain('## 备份过滤规则')
    expect(markdown).toContain('- 过滤模式：`whitelist`（白名单）')
    expect(markdown).toContain('- 预设：`essential`, `no-skills`')
    expect(markdown).toContain('- [glob] `workspace/custom/**` — 额外保留')
    expect(markdown).toContain('- [regex] `^notes/.+$` — 笔记目录')
    expect(markdown).toContain('白名单模式只允许匹配规则的路径进入暂存区')
  })
})
