import assert from "node:assert/strict";

import { formatFilterRulesForMarkdown, generateGitExcludeContent, generateWhitelistCheckScript } from "../lib/backup-filter";
import { buildSkillLink, createDefaultScheduledBackupConfig } from "../lib/ice-boxes";
import { createDisabledEncryptionConfig } from "../lib/backup-encryption";
import { parseSkillConfigSearchParam } from "../lib/skill-document";
import type { IceBoxFilterConfig, IceBoxSkillConfig } from "../types";

const blacklistFilter: IceBoxFilterConfig = {
  mode: "blacklist",
  patterns: [{ pattern: "tmp/**", type: "glob", description: "temp files" }],
  presets: ["nodejs"],
  inheritGitignore: true,
};

const whitelistFilter: IceBoxFilterConfig = {
  mode: "whitelist",
  patterns: [
    { pattern: "workspace/**", type: "glob", description: "workspace" },
    { pattern: "^skills/.+/SKILL\\.md$", type: "regex", description: "skill entry" },
  ],
  presets: ["essential"],
  inheritGitignore: false,
};

const markdown = formatFilterRulesForMarkdown(blacklistFilter);
assert.ok(markdown.includes("## 备份过滤规则"));
assert.ok(markdown.includes("- 过滤模式：`blacklist`（黑名单）"));
assert.ok(markdown.includes("- [glob] `tmp/**` — temp files"));

const gitExclude = generateGitExcludeContent(blacklistFilter);
assert.ok(gitExclude.startsWith("# Generated by Claw-Fridge backup filter\n"));
assert.ok(gitExclude.includes("# Local .gitignore remains effective during git add\n"));
assert.ok(gitExclude.includes("tmp/**\n"));
assert.ok(gitExclude.includes("node_modules/**\n"));

const whitelistScript = generateWhitelistCheckScript(whitelistFilter);
assert.ok(whitelistScript.includes("matches_whitelist_path() {"));
assert.ok(whitelistScript.includes('  case "$path" in'));
assert.ok(whitelistScript.includes("    workspace/**) return 0 ;;") || whitelistScript.includes("    workspace/**) return 0 ;;"));
assert.ok(whitelistScript.includes("grep -E --quiet '^skills/.+/SKILL\\.md$'"));
assert.ok(whitelistScript.trimEnd().endsWith("return 1\n}"));

const createdAt = "2026-03-16T08:00:00.000Z";
const configWithoutFilter: IceBoxSkillConfig = {
  version: 1,
  iceBoxId: "mini-66c2f2",
  iceBoxName: "Mini Test",
  machineId: "mini-66c2f2",
  backupMode: "git-branch",
  repository: "https://github.com/Antarctica26/bingxiang.git",
  branch: "ice-box/mini-66c2f2",
  gitAuthMethod: "https-token",
  gitUsername: "mini",
  uploadPath: null,
  uploadToken: null,
  scheduledBackup: createDefaultScheduledBackupConfig("Asia/Shanghai"),
  encryption: createDisabledEncryptionConfig(createdAt),
  createdAt,
};

const skillLink = buildSkillLink("https://example.com", configWithoutFilter);
const configParam = new URL(skillLink).searchParams.get("config");
assert.ok(configParam, "skill link should contain config param");
const parsedConfig = parseSkillConfigSearchParam(configParam ?? undefined);
assert.ok(parsedConfig.filter, "parsed config should contain filter");
assert.equal(parsedConfig.filter?.mode, "blacklist");
assert.deepEqual(parsedConfig.filter?.presets, ["nodejs", "macos", "sensitive", "cache", "large", "logs", "ide", "python"]);

console.log("validate-skill-generation: ok");
